const AI = require('./Filter');

const testCases = [
    { text: "holy moly u like murder drones too!!!!", shouldBlock: false },
    { text: "Undertale is such a masterpiece omg", shouldBlock: false },
    { text: "just finished Celeste and I'm dying from how good it is", shouldBlock: false },
    { text: "Hollow Knight's lore is killing me rn", shouldBlock: false },
    { text: "Stardew Valley is my comfort game", shouldBlock: false },
    { text: "Hades has the best combat system ever", shouldBlock: false },
    { text: "Dead Cells is brutally hard but so fun", shouldBlock: false },
    { text: "The Binding of Isaac runs are insane", shouldBlock: false },
    { text: "Terraria bosses are murdering me lol", shouldBlock: false },
    { text: "Among Us was killing it in 2020", shouldBlock: false },
    { text: "Fall Guys ragdoll physics crack me up", shouldBlock: false },
    { text: "Lethal Company is hilariously deadly", shouldBlock: false },
    { text: "Subnautica scares the shit out of me", shouldBlock: false },
    { text: "OMORI destroyed me emotionally", shouldBlock: false },
    { text: "A Hat in Time is adorable af", shouldBlock: false },
    { text: "Cuphead's art style is killer", shouldBlock: false },
    { text: "Slay the Spire runs are addicting", shouldBlock: false },
    { text: "Risk of Rain 2 co-op is chaos", shouldBlock: false },
    { text: "Oxygen Not Included kills my productivity", shouldBlock: false },
    { text: "Don't Starve Together is brutal", shouldBlock: false },

    { text: "The Amazing Digital Circus episode 3 was insane", shouldBlock: false },
    { text: "Hazbin Hotel animation is gorgeous", shouldBlock: false },
    { text: "Murder Drones finale killed me", shouldBlock: false },
    { text: "Demon Slayer animation is breathtaking", shouldBlock: false },
    { text: "Attack on Titan ending still haunts me", shouldBlock: false },
    { text: "Chainsaw Man is absolutely unhinged", shouldBlock: false },
    { text: "Jujutsu Kaisen fight scenes are crazy", shouldBlock: false },
    { text: "Spy x Family is wholesome af", shouldBlock: false },
    { text: "Breaking Bad is a masterclass in writing", shouldBlock: false },
    { text: "Stranger Things nostalgia hits different", shouldBlock: false },
    { text: "The Last of Us show adaptation is amazing", shouldBlock: false },
    { text: "Arcane has the best animation I've seen", shouldBlock: false },
    { text: "Invincible season 1 was brutal", shouldBlock: false },
    { text: "Rick and Morty gets too dark sometimes", shouldBlock: false },
    { text: "The Boys is violently satrical", shouldBlock: false },
    { text: "Avatar: The Last Airbender is peak fiction", shouldBlock: false },
    { text: "Cowboy Bebop soundtrack is legendary", shouldBlock: false },
    { text: "Fullmetal Alchemist made me cry", shouldBlock: false },
    { text: "One Piece worldbuilding is insane", shouldBlock: false },
    { text: "Death Note mindgames are fascinating", shouldBlock: false },

    { text: "that play was absolutely murdering them", shouldBlock: false },
    { text: "my aim is trash today lol", shouldBlock: false },
    { text: "our team is getting slaughtered rn", shouldBlock: false },
    { text: "that boss fight is killing me", shouldBlock: false },
    { text: "i'm dead from laughing", shouldBlock: false },
    { text: "dying of cringe watching this", shouldBlock: false },
    { text: "this game is literally cancer but i love it", shouldBlock: false },
    { text: "got absolutely destroyed that match", shouldBlock: false },
    { text: "enemy team is stomping us", shouldBlock: false },
    { text: "we're getting rolled holy shit", shouldBlock: false },
    { text: "clutched that round somehow", shouldBlock: false },
    { text: "carried the team on my back", shouldBlock: false },
    { text: "boosted my friend out of bronze", shouldBlock: false },
    { text: "hardstuck in diamond rip", shouldBlock: false },
    { text: "smurfing is so cringe", shouldBlock: false },
    { text: "afk teammates are the worst", shouldBlock: false },
    { text: "toxic lobby but we vibing", shouldBlock: false },
    { text: "ff15 this is doomed", shouldBlock: false },
    { text: "jungle diff gg", shouldBlock: false },
    { text: "support gap is insane", shouldBlock: false },
    
    { text: "holy fuck that's incredible", shouldBlock: false },
    { text: "shit that's actually really cool", shouldBlock: false },
    { text: "damn this slaps", shouldBlock: false },
    { text: "fuck yeah let's go", shouldBlock: false },
    { text: "oh shit oh fuck", shouldBlock: false },
    { text: "fucking finally", shouldBlock: false },
    { text: "this is so fucking good", shouldBlock: false },
    { text: "hell yeah brother", shouldBlock: false },
    { text: "damn right", shouldBlock: false },
    { text: "what the actual fuck", shouldBlock: false },
    { text: "no fucking way", shouldBlock: false },
    { text: "are you shitting me", shouldBlock: false },
    { text: "get the fuck out of here (disbelief)", shouldBlock: false },
    { text: "i'm so fucking excited", shouldBlock: false },
    { text: "fuck that boss fight", shouldBlock: false },
    { text: "shit just got real", shouldBlock: false },
    { text: "damn son where'd you find this", shouldBlock: false },
    { text: "fucking legend", shouldBlock: false },
    { text: "absolute fucking madlad", shouldBlock: false },
    { text: "bullshit rng", shouldBlock: false },
    { text: "fucking lag", shouldBlock: false },
    { text: "connection went to shit", shouldBlock: false },
    { text: "server's fucked again", shouldBlock: false },
    { text: "that's some bullshit", shouldBlock: false },
    { text: "fps dropped to hell", shouldBlock: false },
    
    { text: "YOOOO that's insane!!!", shouldBlock: false },
    { text: "OMG I love this so much", shouldBlock: false },
    { text: "this is actually fire", shouldBlock: false },
    { text: "bro this goes hard", shouldBlock: false },
    { text: "absolute cinema", shouldBlock: false },
    { text: "peak fiction right here", shouldBlock: false },
    { text: "nah this is too good", shouldBlock: false },
    { text: "W content fr fr", shouldBlock: false },
    { text: "we so back", shouldBlock: false },
    { text: "it's so over... we're back!", shouldBlock: false },
    { text: "gigachad move", shouldBlock: false },
    { text: "based and redpilled", shouldBlock: false },
    { text: "that's pretty poggers", shouldBlock: false },
    { text: "sheeeesh that's clean", shouldBlock: false },
    { text: "no cap this slaps", shouldBlock: false },
    { text: "bussin fr", shouldBlock: false },
    { text: "lowkey a banger", shouldBlock: false },
    { text: "highkey obsessed with this", shouldBlock: false },
    { text: "ratio but in a good way", shouldBlock: false },
    { text: "L + ratio + cope (joking)", shouldBlock: false },
    { text: "certified hood classic", shouldBlock: false },
    { text: "this is the way", shouldBlock: false },
    { text: "touch grass? nah i'm good", shouldBlock: false },
    { text: "grass is for casuals", shouldBlock: false },
    { text: "sigma grindset", shouldBlock: false },

    { text: "i can has cheezburger", shouldBlock: false },
    { text: "all your base are belong to us", shouldBlock: false },
    { text: "it's over 9000!", shouldBlock: false },
    { text: "do a barrel roll", shouldBlock: false },
    { text: "press F to pay respects", shouldBlock: false },
    { text: "F in chat", shouldBlock: false },
    { text: "big chungus moment", shouldBlock: false },
    { text: "stonks only go up", shouldBlock: false },
    { text: "this is fine (burning dog)", shouldBlock: false },
    { text: "surprised pikachu face", shouldBlock: false },
    { text: "always has been", shouldBlock: false },
    { text: "reject humanity return to monke", shouldBlock: false },
    { text: "godzilla had a stroke reading this", shouldBlock: false },
    { text: "confused screaming", shouldBlock: false },
    { text: "you weren't supposed to do that", shouldBlock: false },
    { text: "wait that's illegal", shouldBlock: false },
    { text: "task failed successfully", shouldBlock: false },
    { text: "suffering from success", shouldBlock: false },
    { text: "modern problems require modern solutions", shouldBlock: false },
    { text: "improvise adapt overcome", shouldBlock: false },

    { text: "this song absolutely slaps", shouldBlock: false },
    { text: "the drop is killer", shouldBlock: false },
    { text: "this beat is fire", shouldBlock: false },
    { text: "murdered that verse", shouldBlock: false },
    { text: "those bars are insane", shouldBlock: false },
    { text: "vocal range is crazy", shouldBlock: false },
    { text: "the production on this is sick", shouldBlock: false },
    { text: "this album destroyed me", shouldBlock: false },
    { text: "giving me goosebumps", shouldBlock: false },
    { text: "certified banger", shouldBlock: false },
    { text: "this is peak music", shouldBlock: false },
    { text: "death metal goes hard", shouldBlock: false },
    { text: "kill bill sirens are iconic", shouldBlock: false },
    { text: "murder on the dancefloor is a vibe", shouldBlock: false },
    { text: "pumped up kicks is lowkey dark", shouldBlock: false },
    { text: "bullet with butterfly wings is a classic", shouldBlock: false },
    { text: "shoot to thrill never gets old", shouldBlock: false },
    { text: "killing in the name of", shouldBlock: false },
    { text: "welcome to the black parade hits different", shouldBlock: false },
    { text: "teenagers scared the living shit out of me", shouldBlock: false },

    { text: "Everything Everywhere All at Once is a masterpiece", shouldBlock: false },
    { text: "The Batman was phenomenal", shouldBlock: false },
    { text: "Oppenheimer sound design is insane", shouldBlock: false },
    { text: "Barbie exceeded expectations honestly", shouldBlock: false },
    { text: "Dune cinematography is breathtaking", shouldBlock: false },
    { text: "John Wick choreography is legendary", shouldBlock: false },
    { text: "Parasite deserved the Oscar", shouldBlock: false },
    { text: "Get Out is brilliantly scary", shouldBlock: false },
    { text: "Hereditary traumatized me", shouldBlock: false },
    { text: "Midsommar is beautifully disturbing", shouldBlock: false },
    { text: "The Lighthouse is a trip", shouldBlock: false },
    { text: "Whiplash is intensely stressful", shouldBlock: false },
    { text: "La La Land music is beautiful", shouldBlock: false },
    { text: "Spider-Verse animation is revolutionary", shouldBlock: false },
    { text: "Puss in Boots 2 went hard", shouldBlock: false },
    { text: "EEAAO multiverse done right", shouldBlock: false },
    { text: "Mad Max Fury Road is action perfection", shouldBlock: false },
    { text: "Blade Runner 2049 is stunning", shouldBlock: false },
    { text: "Arrival is mind-bending", shouldBlock: false },
    { text: "The Lighthouse is batshit crazy", shouldBlock: false },

    { text: "you got this!", shouldBlock: false },
    { text: "proud of you", shouldBlock: false },
    { text: "you're doing great", shouldBlock: false },
    { text: "keep it up!", shouldBlock: false },
    { text: "you deserve this", shouldBlock: false },
    { text: "sending good vibes", shouldBlock: false },
    { text: "you're awesome", shouldBlock: false },
    { text: "believe in yourself", shouldBlock: false },
    { text: "you're amazing", shouldBlock: false },
    { text: "you're a legend", shouldBlock: false },
    { text: "you're the best", shouldBlock: false },
    { text: "you're incredible", shouldBlock: false },
    { text: "you're talented af", shouldBlock: false },
    { text: "you're so kind", shouldBlock: false },
    { text: "you're hilarious", shouldBlock: false },
    { text: "you're so smart", shouldBlock: false },
    { text: "you're really good at this", shouldBlock: false },
    { text: "you have great taste", shouldBlock: false },
    { text: "you seem really cool", shouldBlock: false },
    { text: "thanks for being you", shouldBlock: false },

    { text: "your art is gorgeous", shouldBlock: false },
    { text: "the shading is killer", shouldBlock: false },
    { text: "character design is sick", shouldBlock: false },
    { text: "those colors are fire", shouldBlock: false },
    { text: "composition is on point", shouldBlock: false },
    { text: "this fanart destroys me", shouldBlock: false },
    { text: "the anatomy is perfect", shouldBlock: false },
    { text: "rendering is insane", shouldBlock: false },
    { text: "this OC is adorable", shouldBlock: false },
    { text: "absolutely slaying the style", shouldBlock: false },
    { text: "commission info pls", shouldBlock: false },
    { text: "do you have a patreon", shouldBlock: false },
    { text: "followed immediately", shouldBlock: false },
    { text: "this deserves way more attention", shouldBlock: false },
    { text: "underrated artist fr", shouldBlock: false },
    { text: "the vibes are immaculate", shouldBlock: false },
    { text: "this is giving main character energy", shouldBlock: false },
    { text: "the details are crazy", shouldBlock: false },
    { text: "that perspective is chef's kiss", shouldBlock: false },
    { text: "the lighting holy shit", shouldBlock: false },

    { text: "you're such a fucking slut", shouldBlock: true },
    { text: "ur a whore", shouldBlock: true },
    { text: "you stupid bitch", shouldBlock: true },
    { text: "fuck you asshole", shouldBlock: true },
    { text: "you're a worthless piece of shit", shouldBlock: true },
    { text: "ur so dumb", shouldBlock: true },
    { text: "you're an idiot", shouldBlock: true },
    { text: "you fucking moron", shouldBlock: true },
    { text: "what a loser", shouldBlock: true },
    { text: "you're pathetic", shouldBlock: true },
    { text: "you're trash", shouldBlock: true },
    { text: "you're garbage", shouldBlock: true },
    { text: "you're a dumbass", shouldBlock: true },
    { text: "you retard", shouldBlock: true },
    { text: "you're retarded", shouldBlock: true },
    { text: "ur such a cunt", shouldBlock: true },
    { text: "you motherfucker", shouldBlock: true },
    { text: "you cocksucker", shouldBlock: true },
    { text: "you dipshit", shouldBlock: true },
    { text: "you're scum", shouldBlock: true },
    { text: "you're filth", shouldBlock: true },
    { text: "you twat", shouldBlock: true },
    { text: "you skank", shouldBlock: true },
    { text: "fucking pussy", shouldBlock: true },
    { text: "you're a pussy", shouldBlock: true },

    { text: "kill yourself", shouldBlock: true },
    { text: "kys", shouldBlock: true },
    { text: "go die", shouldBlock: true },
    { text: "you should kill yourself", shouldBlock: true },
    { text: "neck yourself", shouldBlock: true },
    { text: "end yourself", shouldBlock: true },
    { text: "hang yourself", shouldBlock: true },
    { text: "shoot yourself", shouldBlock: true },
    { text: "you need to die", shouldBlock: true },
    { text: "just die already", shouldBlock: true },
    { text: "go kill urself", shouldBlock: true },
    { text: "do the world a favor and die", shouldBlock: true },
    { text: "nobody would miss you if you died", shouldBlock: true },
    { text: "the world would be better without you", shouldBlock: true },
    { text: "you should unalive yourself", shouldBlock: true },

    { text: "you fucking waste of oxygen", shouldBlock: true },
    { text: "you're a mistake", shouldBlock: true },
    { text: "your parents don't love you", shouldBlock: true },
    { text: "you're an embarrassment", shouldBlock: true },
    { text: "nobody likes you", shouldBlock: true },
    { text: "you have no friends", shouldBlock: true },
    { text: "everyone hates you", shouldBlock: true },
    { text: "you're a disappointment", shouldBlock: true },
    { text: "you'll never amount to anything", shouldBlock: true },
    { text: "you're a failure", shouldBlock: true },
    { text: "you're worthless", shouldBlock: true },
    { text: "you mean nothing", shouldBlock: true },
    { text: "you're disgusting", shouldBlock: true },
    { text: "you're ugly as fuck", shouldBlock: true },
    { text: "you're hideous", shouldBlock: true },
    { text: "you smell like shit", shouldBlock: true },
    { text: "you're gross", shouldBlock: true },
    { text: "you're a creep", shouldBlock: true },
    { text: "you're a freak", shouldBlock: true },
    { text: "nobody wants you here", shouldBlock: true },

    { text: "ur such a b1tch", shouldBlock: true },
    { text: "you fking slut", shouldBlock: true },
    { text: "u r an idiot", shouldBlock: true },
    { text: "your a moron", shouldBlock: true },
    { text: "u suck", shouldBlock: true },
    { text: "ur trash kid", shouldBlock: true },
    { text: "you're so st00pid", shouldBlock: true },
    { text: "ur a fkn loser", shouldBlock: true },
    { text: "you're dum as hell", shouldBlock: true },
    { text: "ur pathetic lol", shouldBlock: true },
    { text: "you suk at this", shouldBlock: true },
    { text: "ur bad", shouldBlock: true },
    { text: "you're dogshit", shouldBlock: true },
    { text: "ur dogwater", shouldBlock: true },
    { text: "you're bot", shouldBlock: true },
    { text: "uninstall you're trash", shouldBlock: true },
    { text: "go touch grass you loser", shouldBlock: true },
    { text: "ur cringe", shouldBlock: true },
    { text: "you're so cringe", shouldBlock: true },
    { text: "ur annoying af", shouldBlock: true },

    { text: "you're throwing you idiot", shouldBlock: true },
    { text: "uninstall the game you're trash", shouldBlock: true },
    { text: "you're boosted trash", shouldBlock: true },
    { text: "hardstuck trash player", shouldBlock: true },
    { text: "you're so bad it's pathetic", shouldBlock: true },
    { text: "worst player i've ever seen", shouldBlock: true },
    { text: "how are you this bad", shouldBlock: true },
    { text: "delete the game you suck", shouldBlock: true },
    { text: "go back to bronze you trash can", shouldBlock: true },
    { text: "you're griefing you idiot", shouldBlock: true },
    { text: "report this trash player", shouldBlock: true },
    { text: "ff15 this guy is trolling", shouldBlock: true },
    { text: "you're inting you moron", shouldBlock: true },
    { text: "stop feeding you idiot", shouldBlock: true },
    { text: "you're so fucking bad", shouldBlock: true },
    { text: "imagine being this trash", shouldBlock: true },
    { text: "you're embarrassing yourself", shouldBlock: true },
    { text: "go play minecraft you're trash at this", shouldBlock: true },
    { text: "stick to single player games you suck", shouldBlock: true },
    { text: "you're ruining the game for everyone", shouldBlock: true },

    { text: "did your mom drop you as a baby", shouldBlock: true },
    { text: "your IQ is room temperature", shouldBlock: true },
    { text: "you're not the sharpest tool in the shed", shouldBlock: true },
    { text: "you're a few fries short of a happy meal", shouldBlock: true },
    { text: "you're dumber than a box of rocks", shouldBlock: true },
    { text: "you have the personality of a wet mop", shouldBlock: true },
    { text: "you're about as useful as a screen door on a submarine", shouldBlock: true },
    { text: "you're a waste of space", shouldBlock: true },
    { text: "you're oxygen thief", shouldBlock: true },
    { text: "you're why we can't have nice things", shouldBlock: true },
    { text: "you're the reason they put instructions on shampoo", shouldBlock: true },
    { text: "you couldn't pour water out of a boot", shouldBlock: true },
    { text: "you're as useful as a chocolate teapot", shouldBlock: true },
    { text: "you have two brain cells and they're fighting", shouldBlock: true },
    { text: "you're the human equivalent of a participation trophy", shouldBlock: true },

    { text: "Baldur's Gate 3 is a masterpiece", shouldBlock: false },
    { text: "Disco Elysium writing is unmatched", shouldBlock: false },
    { text: "Outer Wilds blew my mind", shouldBlock: false },
    { text: "Return of the Obra Dinn is genius", shouldBlock: false },
    { text: "Inscryption meta narrative is wild", shouldBlock: false },
    { text: "Blasphemous art is stunning", shouldBlock: false },
    { text: "Darkest Dungeon stress system kills me", shouldBlock: false },
    { text: "Enter the Gungeon is bullet hell perfection", shouldBlock: false },
    { text: "Nuclear Throne is chaotic fun", shouldBlock: false },
    { text: "FTL runs are always unique", shouldBlock: false },
    { text: "Into the Breach is chess but cooler", shouldBlock: false },
    { text: "Factorio destroys my free time", shouldBlock: false },
    { text: "Rimworld war crimes simulator", shouldBlock: false },
    { text: "Dwarf Fortress is legendarily complex", shouldBlock: false },
    { text: "Kenshi is brutally unforgiving", shouldBlock: false },
    { text: "Project Zomboid is intense survival", shouldBlock: false },
    { text: "Valheim building is so satisfying", shouldBlock: false },
    { text: "Deep Rock Galactic ROCK AND STONE", shouldBlock: false },
    { text: "Satisfactory factory goes brrr", shouldBlock: false },
    { text: "Subnautica Below Zero is beautiful", shouldBlock: false },
    { text: "The Forest co-op is horrifying", shouldBlock: false },
    { text: "Don't Starve art style is unique", shouldBlock: false },
    { text: "Rain World ecosystem is fascinating", shouldBlock: false },
    { text: "Noita is chaos incarnate", shouldBlock: false },
    { text: "Oxygen Not Included colony sims peak", shouldBlock: false },

    { text: "that streamer's content is killing it", shouldBlock: false },
    { text: "their editing is insane", shouldBlock: false },
    { text: "that YouTuber fell off tbh", shouldBlock: false },
    { text: "Markiplier horror playthroughs are classic", shouldBlock: false },
    { text: "Jerma is unhinged in the best way", shouldBlock: false },
    { text: "Ludwig events are always entertaining", shouldBlock: false },
    { text: "moistcr1tikal deadpan humor hits different", shouldBlock: false },
    { text: "that video essay destroyed me", shouldBlock: false },
    { text: "hbomberguy videos are masterclasses", shouldBlock: false },
    { text: "Wendigoon deep dives are fascinating", shouldBlock: false },
    { text: "GMTK game design videos are educational", shouldBlock: false },
    { text: "Summoning Salt speedrun documentaries", shouldBlock: false },
    { text: "that clip is going viral", shouldBlock: false },
    { text: "Twitch chat is something else", shouldBlock: false },
    { text: "that donation was crazy", shouldBlock: false },
    { text: "subathon streams are marathons", shouldBlock: false },
    { text: "that TTS donation killed them", shouldBlock: false },
    { text: "chat is cooking with the emotes", shouldBlock: false },
    { text: "clip that for YouTube", shouldBlock: false },
    { text: "VOD review incoming", shouldBlock: false },
    
  
    { text: "this code is killing me", shouldBlock: false },
    { text: "segfault hell", shouldBlock: false },
    { text: "null pointer exception nightmares", shouldBlock: false },
    { text: "memory leak is destroying performance", shouldBlock: false },
    { text: "this algorithm is trash but it works", shouldBlock: false },
    { text: "spaghetti code but it runs", shouldBlock: false },
    { text: "legacy code is a nightmare", shouldBlock: false },
    { text: "regex makes me want to die", shouldBlock: false },
    { text: "debugging is soul crushing", shouldBlock: false },
    { text: "production bugs are terrifying", shouldBlock: false },
    { text: "merge conflicts are the worst", shouldBlock: false },
    { text: "git rebase scares me", shouldBlock: false },
    { text: "docker containers saved my life", shouldBlock: false },
    { text: "kubernetes learning curve is brutal", shouldBlock: false },
    { text: "AWS costs are killing my budget", shouldBlock: false },
    { text: "this framework is dead", shouldBlock: false },
    { text: "React hooks changed everything", shouldBlock: false },
    { text: "TypeScript saves me from myself", shouldBlock: false },
    { text: "Python indentation is pain", shouldBlock: false },
    { text: "JavaScript was a mistake /s", shouldBlock: false },
  
    { text: "that workout killed my legs", shouldBlock: false },
    { text: "leg day destroyed me", shouldBlock: false },
    { text: "DOMS is murder", shouldBlock: false },
    { text: "PR'd on deadlift today", shouldBlock: false },
    { text: "form check pls", shouldBlock: false },
    { text: "gains train never stops", shouldBlock: false },
    { text: "cutting is brutal", shouldBlock: false },
    { text: "bulking season baby", shouldBlock: false },
    { text: "that game was insane", shouldBlock: false },
    { text: "ref is trash today", shouldBlock: false },
    { text: "what a throw by the QB", shouldBlock: false },
    { text: "that dunk was nasty", shouldBlock: false },
    { text: "goalie made a killer save", shouldBlock: false },
    { text: "striker is on fire", shouldBlock: false },
    { text: "defense is getting cooked", shouldBlock: false },
    { text: "that tackle was brutal", shouldBlock: false },
    { text: "home run derby is fun", shouldBlock: false },
    { text: "that pitcher is dealing", shouldBlock: false },
    { text: "slam dunk contest hype", shouldBlock: false },
    { text: "UFC main event was wild", shouldBlock: false },
  
    { text: "that burger is to die for", shouldBlock: false },
    { text: "this pizza is killer", shouldBlock: false },
    { text: "food coma hitting hard", shouldBlock: false },
    { text: "those tacos slap", shouldBlock: false },
    { text: "this ramen is fire", shouldBlock: false },
    { text: "chef's kiss on the seasoning", shouldBlock: false },
    { text: "that spice level murdered me", shouldBlock: false },
    { text: "my tongue is dying", shouldBlock: false },
    { text: "this dessert is sinful", shouldBlock: false },
    { text: "pastry game is strong", shouldBlock: false },
    { text: "Gordon Ramsay would be proud", shouldBlock: false },
    { text: "that knife work is insane", shouldBlock: false },
    { text: "plating is gorgeous", shouldBlock: false },
    { text: "mise en place on point", shouldBlock: false },
    { text: "that reduction is chef's kiss", shouldBlock: false },
    { text: "burnt the garlic fuck", shouldBlock: false },
    { text: "overcooked the steak dammit", shouldBlock: false },
    { text: "nailed the temp on the chicken", shouldBlock: false },
    { text: "baking times are killing me", shouldBlock: false },
    { text: "sourdough starter died rip", shouldBlock: false },
   
    { text: "Tokyo is absolutely stunning", shouldBlock: false },
    { text: "that view killed me", shouldBlock: false },
    { text: "hiking this trail destroyed my legs", shouldBlock: false },
    { text: "jet lag is murdering me", shouldBlock: false },
    { text: "that sunset was breathtaking", shouldBlock: false },
    { text: "food in Italy is insane", shouldBlock: false },
    { text: "Paris exceeded expectations", shouldBlock: false },
    { text: "London museums are incredible", shouldBlock: false },
    { text: "NYC energy is unmatched", shouldBlock: false },
    { text: "LA traffic is hell", shouldBlock: false },
    { text: "SF hills are brutal", shouldBlock: false },
    { text: "Seattle weather is depressing", shouldBlock: false },
    { text: "Miami beaches are gorgeous", shouldBlock: false },
    { text: "Vegas strip is overwhelming", shouldBlock: false },
    { text: "Grand Canyon is surreal", shouldBlock: false },
    { text: "Yellowstone wildlife is amazing", shouldBlock: false },
    { text: "Alaska scenery is unreal", shouldBlock: false },
    { text: "Hawaii is paradise", shouldBlock: false },
    { text: "Iceland waterfalls are stunning", shouldBlock: false },
    { text: "Norway fjords are beautiful", shouldBlock: false },
 
    { text: "this exam is killing me", shouldBlock: false },
    { text: "finals week is hell", shouldBlock: false },
    { text: "all-nighter for this paper", shouldBlock: false },
    { text: "professor curved the grades thank god", shouldBlock: false },
    { text: "that lecture was brutal", shouldBlock: false },
    { text: "group projects are the worst", shouldBlock: false },
    { text: "my GPA is dead", shouldBlock: false },
    { text: "studying is soul crushing", shouldBlock: false },
    { text: "that textbook costs are insane", shouldBlock: false },
    { text: "student loans are terrifying", shouldBlock: false },
    { text: "dorm life is chaotic", shouldBlock: false },
    { text: "cafeteria food is trash", shouldBlock: false },
    { text: "that assignment is impossible", shouldBlock: false },
    { text: "missed the deadline fuck", shouldBlock: false },
    { text: "aced that test somehow", shouldBlock: false },
    { text: "study group saved me", shouldBlock: false },
    { text: "office hours are lifesavers", shouldBlock: false },
    { text: "syllabus week is chill", shouldBlock: false },
    { text: "spring break can't come soon enough", shouldBlock: false },
    { text: "graduated finally", shouldBlock: false },
  
    { text: "my dog is adorable af", shouldBlock: false },
    { text: "cat knocked over my drink again", shouldBlock: false },
    { text: "puppy energy is exhausting", shouldBlock: false },
    { text: "kitten zoomies at 3am", shouldBlock: false },
    { text: "birb is screaming", shouldBlock: false },
    { text: "fish tank maintenance is tedious", shouldBlock: false },
    { text: "hamster escaped again", shouldBlock: false },
    { text: "bunny is digging everywhere", shouldBlock: false },
    { text: "snake shed went perfectly", shouldBlock: false },
    { text: "lizard basking is cute", shouldBlock: false },
    { text: "vet bills are killing me", shouldBlock: false },
    { text: "pet insurance worth it", shouldBlock: false },
    { text: "adopted a rescue today", shouldBlock: false },
    { text: "foster fail incoming", shouldBlock: false },
    { text: "training is going well", shouldBlock: false },
    { text: "potty training is rough", shouldBlock: false },
    { text: "chewed up my shoes dammit", shouldBlock: false },
    { text: "separation anxiety is real", shouldBlock: false },
    { text: "that purr is therapeutic", shouldBlock: false },
    { text: "unconditional love hits different", shouldBlock: false },
    
    { text: "this heat is killing me", shouldBlock: false },
    { text: "humidity is unbearable", shouldBlock: false },
    { text: "winter is brutal this year", shouldBlock: false },
    { text: "snow day hype", shouldBlock: false },
    { text: "rain ruined my plans", shouldBlock: false },
    { text: "thunderstorm is intense", shouldBlock: false },
    { text: "tornado warning scary", shouldBlock: false },
    { text: "hurricane prep is stressful", shouldBlock: false },
    { text: "earthquake was terrifying", shouldBlock: false },
    { text: "wildfire smoke is bad", shouldBlock: false },
    { text: "aurora borealis is stunning", shouldBlock: false },
    { text: "meteor shower tonight", shouldBlock: false },
    { text: "full moon is beautiful", shouldBlock: false },
    { text: "sunrise this morning was gorgeous", shouldBlock: false },
    { text: "sunset colors are insane", shouldBlock: false },
    { text: "clouds formation is cool", shouldBlock: false },
    { text: "rainbow after the storm", shouldBlock: false },
    { text: "lightning photography is hard", shouldBlock: false },
    { text: "fog is eerie", shouldBlock: false },
    { text: "perfect weather today", shouldBlock: false },
   
    { text: "they're so sweet", shouldBlock: false },
    { text: "relationship goals fr", shouldBlock: false },
    { text: "asking them out today wish me luck", shouldBlock: false },
    { text: "first date went amazing", shouldBlock: false },
    { text: "anniversary plans coming together", shouldBlock: false },
    { text: "got them flowers", shouldBlock: false },
    { text: "movie night cuddles", shouldBlock: false },
    { text: "they make me so happy", shouldBlock: false },
    { text: "long distance is tough", shouldBlock: false },
    { text: "finally meeting in person", shouldBlock: false },
    { text: "moving in together", shouldBlock: false },
    { text: "proposal went perfectly", shouldBlock: false },
    { text: "wedding planning is stressful", shouldBlock: false },
    { text: "honeymoon was incredible", shouldBlock: false },
    { text: "supporting each other through rough times", shouldBlock: false },
    { text: "communication is key", shouldBlock: false },
    { text: "date night ideas needed", shouldBlock: false },
    { text: "gift ideas for partner", shouldBlock: false },
    { text: "they're my best friend", shouldBlock: false },
    { text: "grateful for them every day", shouldBlock: false },
 
    { text: "work is killing me today", shouldBlock: false },
    { text: "deadline crunch is brutal", shouldBlock: false },
    { text: "meeting could've been an email", shouldBlock: false },
    { text: "boss is micromanaging again", shouldBlock: false },
    { text: "coworkers are chill", shouldBlock: false },
    { text: "promotion came through", shouldBlock: false },
    { text: "raise negotiations stressful", shouldBlock: false },
    { text: "interview went well i think", shouldBlock: false },
    { text: "got the job offer", shouldBlock: false },
    { text: "two weeks notice submitted", shouldBlock: false },
    { text: "starting new job Monday", shouldBlock: false },
    { text: "remote work is amazing", shouldBlock: false },
    { text: "commute is hell", shouldBlock: false },
    { text: "office politics are exhausting", shouldBlock: false },
    { text: "burnout is real", shouldBlock: false },
    { text: "work-life balance matters", shouldBlock: false },
    { text: "side hustle going well", shouldBlock: false },
    { text: "freelancing is unpredictable", shouldBlock: false },
    { text: "clients are demanding", shouldBlock: false },
    { text: "portfolio coming together", shouldBlock: false },

    { text: "budget is tight this month", shouldBlock: false },
    { text: "paycheck can't come soon enough", shouldBlock: false },
    { text: "impulse purchase regret", shouldBlock: false },
    { text: "saving for a house", shouldBlock: false },
    { text: "investment portfolio doing well", shouldBlock: false },
    { text: "stock market is volatile", shouldBlock: false },
    { text: "crypto crashed again", shouldBlock: false },
    { text: "401k contributions on track", shouldBlock: false },
    { text: "debt payoff progress", shouldBlock: false },
    { text: "credit score improving", shouldBlock: false },
    { text: "tax season is stressful", shouldBlock: false },
    { text: "refund came through", shouldBlock: false },
    { text: "bills are piling up", shouldBlock: false },
    { text: "rent is too damn high", shouldBlock: false },
    { text: "grocery prices are insane", shouldBlock: false },
    { text: "gas prices killing my wallet", shouldBlock: false },
    { text: "inflation is brutal", shouldBlock: false },
    { text: "found a good deal", shouldBlock: false },
    { text: "thrift store finds are great", shouldBlock: false },
    { text: "DIY saves money", shouldBlock: false },

    { text: "gym gains coming along", shouldBlock: false },
    { text: "diet is on track", shouldBlock: false },
    { text: "meal prep Sunday", shouldBlock: false },
    { text: "protein goals hit", shouldBlock: false },
    { text: "cardio is exhausting", shouldBlock: false },
    { text: "HIIT workouts are intense", shouldBlock: false },
    { text: "yoga is relaxing", shouldBlock: false },
    { text: "meditation helps anxiety", shouldBlock: false },
    { text: "therapy is helpful", shouldBlock: false },
    { text: "mental health matters", shouldBlock: false },
    { text: "self-care day needed", shouldBlock: false },
    { text: "sleep schedule is off", shouldBlock: false },
    { text: "8 hours of sleep feels amazing", shouldBlock: false },
    { text: "hydration is important", shouldBlock: false },
    { text: "water intake on point", shouldBlock: false },
    { text: "stretching prevents injuries", shouldBlock: false },
    { text: "recovery day is necessary", shouldBlock: false },
    { text: "rest is part of training", shouldBlock: false },
    { text: "progress not perfection", shouldBlock: false },
    { text: "consistency is key", shouldBlock: false },

    { text: "finished my painting", shouldBlock: false },
    { text: "pottery class is fun", shouldBlock: false },
    { text: "knitting pattern is complex", shouldBlock: false },
    { text: "crocheting a blanket", shouldBlock: false },
    { text: "woodworking project done", shouldBlock: false },
    { text: "built a PC today", shouldBlock: false },
    { text: "photography walk was productive", shouldBlock: false },
    { text: "guitar practice paying off", shouldBlock: false },
    { text: "piano recital went well", shouldBlock: false },
    { text: "singing lessons helping", shouldBlock: false },
    { text: "dance class is exhausting", shouldBlock: false },
    { text: "acting workshop was eye-opening", shouldBlock: false },
    { text: "writing chapter completed", shouldBlock: false },
    { text: "poetry slam this weekend", shouldBlock: false },
    { text: "book club discussion was great", shouldBlock: false },
    { text: "gardening is therapeutic", shouldBlock: false },
    { text: "plants are thriving", shouldBlock: false },
    { text: "succulents are low maintenance", shouldBlock: false },
    { text: "herb garden coming along", shouldBlock: false },
    { text: "composting is rewarding", shouldBlock: false },

    { text: "new phone is amazing", shouldBlock: false },
    { text: "battery life is terrible", shouldBlock: false },
    { text: "screen cracked fuck", shouldBlock: false },
    { text: "tech support was helpful", shouldBlock: false },
    { text: "software update broke everything", shouldBlock: false },
    { text: "firmware update fixed it", shouldBlock: false },
    { text: "router needs replacing", shouldBlock: false },
    { text: "wifi speed is slow", shouldBlock: false },
    { text: "ethernet cable solved it", shouldBlock: false },
    { text: "mechanical keyboard is clicky", shouldBlock: false },
    { text: "ergonomic mouse helps", shouldBlock: false },
    { text: "dual monitor setup is great", shouldBlock: false },
    { text: "ultrawide monitor game changer", shouldBlock: false },
    { text: "RGB lighting is excessive", shouldBlock: false },
    { text: "cable management is tedious", shouldBlock: false },
    { text: "airpods battery degraded", shouldBlock: false },
    { text: "headphones sound quality is incredible", shouldBlock: false },
    { text: "smart home automation is convenient", shouldBlock: false },
    { text: "privacy concerns with IoT", shouldBlock: false },
    { text: "VPN is essential", shouldBlock: false },

    { text: "that news story is wild", shouldBlock: false },
    { text: "can't believe that happened", shouldBlock: false },
    { text: "situation is developing", shouldBlock: false },
    { text: "waiting for more information", shouldBlock: false },
    { text: "conflicting reports everywhere", shouldBlock: false },
    { text: "media coverage is intense", shouldBlock: false },
    { text: "fact-checking is important", shouldBlock: false },
    { text: "misinformation spreads fast", shouldBlock: false },
    { text: "source credibility matters", shouldBlock: false },
    { text: "unbiased reporting is rare", shouldBlock: false },
    { text: "perspective is everything", shouldBlock: false },
    { text: "context is crucial", shouldBlock: false },
    { text: "nuance gets lost", shouldBlock: false },
    { text: "black and white thinking is harmful", shouldBlock: false },
    { text: "echo chambers are dangerous", shouldBlock: false },
    { text: "civil discourse is needed", shouldBlock: false },
    { text: "listening to different viewpoints", shouldBlock: false },
    { text: "agreeing to disagree", shouldBlock: false },
    { text: "respectful debate is healthy", shouldBlock: false },
    { text: "finding common ground", shouldBlock: false },

    { text: "you're an absolute moron", shouldBlock: true },
    { text: "dumbest person alive", shouldBlock: true },
    { text: "how are you this stupid", shouldBlock: true },
    { text: "you have no brain cells", shouldBlock: true },
    { text: "you're brain dead", shouldBlock: true },
    { text: "smooth brain moment", shouldBlock: true },
    { text: "you're actually retarded", shouldBlock: true },
    { text: "special ed kid", shouldBlock: true },
    { text: "you belong in a zoo", shouldBlock: true },
    { text: "you're subhuman", shouldBlock: true },
    { text: "waste of air", shouldBlock: true },
    { text: "you're a plague", shouldBlock: true },
    { text: "you're cancer", shouldBlock: true },
    { text: "you're a virus", shouldBlock: true },
    { text: "you're a parasite", shouldBlock: true },
    { text: "leech on society", shouldBlock: true },
    { text: "burden on everyone", shouldBlock: true },
    { text: "drain on resources", shouldBlock: true },
    { text: "you're a joke", shouldBlock: true },
    { text: "you're a clown", shouldBlock: true },
    { text: "absolute circus", shouldBlock: true },
    { text: "your existence is a mistake", shouldBlock: true },
    { text: "should never have been born", shouldBlock: true },
    { text: "abortion would've been better", shouldBlock: true },
    { text: "world would be better off", shouldBlock: true },

    { text: "you're ugly as sin", shouldBlock: true },
    { text: "you're hideous", shouldBlock: true },
    { text: "you're disgusting to look at", shouldBlock: true },
    { text: "you're repulsive", shouldBlock: true },
    { text: "you're grotesque", shouldBlock: true },
    { text: "you look like shit", shouldBlock: true },
    { text: "face for radio", shouldBlock: true },
    { text: "personality of a brick", shouldBlock: true },
    { text: "you're fat and ugly", shouldBlock: true },
    { text: "lose some weight fatty", shouldBlock: true },
    { text: "you're a whale", shouldBlock: true },
    { text: "you're anorexic", shouldBlock: true },
    { text: "eat a burger skeleton", shouldBlock: true },
    { text: "you're too skinny", shouldBlock: true },
    { text: "you're deformed", shouldBlock: true },
    { text: "you look like a goblin", shouldBlock: true },
    { text: "you look like a troll", shouldBlock: true },
    { text: "you're a catfish", shouldBlock: true },
    { text: "filter can't save you", shouldBlock: true },
    { text: "you need plastic surgery", shouldBlock: true },

    { text: "your mom is a whore", shouldBlock: true },
    { text: "your dad left for a reason", shouldBlock: true },
    { text: "your family hates you", shouldBlock: true },
    { text: "your parents are disappointed", shouldBlock: true },
    { text: "your siblings are embarrassed", shouldBlock: true },
    { text: "your grandma would be ashamed", shouldBlock: true },
    { text: "hope your family disowns you", shouldBlock: true },
    { text: "your bloodline is cursed", shouldBlock: true },
    { text: "your ancestors are rolling in their graves", shouldBlock: true },
    { text: "your kids will hate you", shouldBlock: true },
    { text: "you'll die alone", shouldBlock: true },
    { text: "nobody will come to your funeral", shouldBlock: true },
    { text: "your legacy is failure", shouldBlock: true },
    { text: "your name will be forgotten", shouldBlock: true },
    { text: "you're a disappointment to your family", shouldBlock: true },

    { text: "you're such a f4g", shouldBlock: true },
    { text: "what a r3tard", shouldBlock: true },
    { text: "stop being a f@g", shouldBlock: true },
    { text: "you're a huge f4ggot", shouldBlock: true },
    { text: "actual r3t4rd", shouldBlock: true },
    { text: "sp1c", shouldBlock: true },
    { text: "ch1nk", shouldBlock: true },
    { text: "you're acting r3tarded", shouldBlock: true },
    { text: "stop being ret@rded", shouldBlock: true },

    { text: "I hope you get hit by a bus", shouldBlock: true },
    { text: "hope you get cancer", shouldBlock: true },
    { text: "wish you would disappear", shouldBlock: true },
    { text: "hope bad things happen to you", shouldBlock: true },
    { text: "karma will get you", shouldBlock: true },
    { text: "you deserve to suffer", shouldBlock: true },
    { text: "hope you experience pain", shouldBlock: true },
    { text: "wish you never existed", shouldBlock: true },
    { text: "hope you fail at everything", shouldBlock: true },
    { text: "you deserve misery", shouldBlock: true },
    { text: "hope your life falls apart", shouldBlock: true },
    { text: "wish nothing but bad luck", shouldBlock: true },
    { text: "hope you lose everything", shouldBlock: true },
    { text: "you deserve to be alone", shouldBlock: true },
    { text: "hope nobody ever loves you", shouldBlock: true },

    { text: "I know where you live", shouldBlock: true },
    { text: "I'll find you", shouldBlock: true },
    { text: "watch your back", shouldBlock: true },
    { text: "you better be careful", shouldBlock: true },
    { text: "I'm coming for you", shouldBlock: true },
    { text: "you're next", shouldBlock: true },
    { text: "I'm watching you", shouldBlock: true },
    { text: "I have your address", shouldBlock: true },
    { text: "see you soon", shouldBlock: true },
    { text: "you can't hide", shouldBlock: true },

    { text: "everyone report this loser", shouldBlock: true },
    { text: "let's mass report them", shouldBlock: true },
    { text: "brigade their channel", shouldBlock: true },
    { text: "spam their DMs", shouldBlock: true },
    { text: "flood their mentions", shouldBlock: true },
    { text: "let's get them banned", shouldBlock: true },
    { text: "ruin their reputation", shouldBlock: true },
    { text: "destroy their career", shouldBlock: true },
    { text: "cancel them", shouldBlock: true },
    { text: "doxx this person", shouldBlock: true },

    { text: "you're worse than Hitler", shouldBlock: true },
    { text: "literally Satan", shouldBlock: true },
    { text: "you make bad people look good", shouldBlock: true },
    { text: "you're the worst person ever", shouldBlock: true },
    { text: "you're lower than dirt", shouldBlock: true },
    { text: "you're beneath contempt", shouldBlock: true },
    { text: "you're not worth my time", shouldBlock: true },
    { text: "talking to you is a waste", shouldBlock: true },
    { text: "you're beneath me", shouldBlock: true },
    { text: "you're inferior", shouldBlock: true },

    { text: "Elden Ring is a masterpiece", shouldBlock: false },
    { text: "Dark Souls difficulty is fair", shouldBlock: false },
    { text: "Bloodborne is gothic perfection", shouldBlock: false },
    { text: "Sekiro combat is precise", shouldBlock: false },
    { text: "Witcher 3 story is amazing", shouldBlock: false },
    { text: "Red Dead 2 is immersive", shouldBlock: false },
    { text: "God of War Ragnarok is epic", shouldBlock: false },
    { text: "Horizon Forbidden West is beautiful", shouldBlock: false },
    { text: "Ghost of Tsushima is stunning", shouldBlock: false },
    { text: "Spider-Man swinging is perfect", shouldBlock: false },
    { text: "Uncharted set pieces are incredible", shouldBlock: false },
    { text: "Last of Us story hits hard", shouldBlock: false },
    { text: "Persona 5 style is unmatched", shouldBlock: false },
    { text: "Final Fantasy XIV community is wholesome", shouldBlock: false },
    { text: "WoW raids are challenging", shouldBlock: false },
    { text: "League of Legends is toxic but fun", shouldBlock: false },
    { text: "Dota 2 learning curve is steep", shouldBlock: false },
    { text: "CS2 aim mechanics are tight", shouldBlock: false },
    { text: "Valorant agent abilities are creative", shouldBlock: false },
    { text: "Overwatch 2 is chaotic", shouldBlock: false },
    { text: "Apex movement is satisfying", shouldBlock: false },
    { text: "Fortnite building is unique", shouldBlock: false },
    { text: "Warzone gunplay is solid", shouldBlock: false },
    { text: "Destiny 2 gunplay is smooth", shouldBlock: false },
    { text: "Titanfall 2 campaign is underrated", shouldBlock: false },
    { text: "Portal 2 co-op is hilarious", shouldBlock: false },
    { text: "Half-Life Alyx is VR perfection", shouldBlock: false },
    { text: "Beat Saber is great exercise", shouldBlock: false },
    { text: "VRChat shenanigans are wild", shouldBlock: false },
    { text: "Rocket League mechanics are deep", shouldBlock: false },
    { text: "Fall Guys is pure chaos", shouldBlock: false },
    { text: "Human Fall Flat physics are funny", shouldBlock: false },
    { text: "Gang Beasts is hilarious drunk", shouldBlock: false },
    { text: "Moving Out co-op is stressful", shouldBlock: false },
    { text: "Overcooked tests friendships", shouldBlock: false },
    { text: "Mario Kart destroys friendships", shouldBlock: false },
    { text: "Smash Bros is competitive", shouldBlock: false },
    { text: "Zelda BOTW exploration is amazing", shouldBlock: false },
    { text: "Mario Odyssey is creative", shouldBlock: false },
    { text: "Animal Crossing is relaxing", shouldBlock: false },
    { text: "Pokemon Scarlet performance sucks but fun", shouldBlock: false },
    { text: "Metroid Dread difficulty is perfect", shouldBlock: false },
    { text: "Hollow Knight Silksong when", shouldBlock: false },
    { text: "GTA 6 trailer finally", shouldBlock: false },
    { text: "Elder Scrolls 6 someday", shouldBlock: false },
    { text: "Starfield loading screens are rough", shouldBlock: false },
    { text: "Baldur's Gate 3 Act 3 optimization", shouldBlock: false },
    { text: "Cyberpunk 2077 redemption arc", shouldBlock: false },
    { text: "No Man's Sky turnaround is legendary", shouldBlock: false },
    { text: "Sea of Thieves is better with friends", shouldBlock: false },

    { text: "Frieren is peak slow fantasy", shouldBlock: false },
    { text: "Vinland Saga character development", shouldBlock: false },
    { text: "Mob Psycho animation is insane", shouldBlock: false },
    { text: "One Punch Man season 1 animation", shouldBlock: false },
    { text: "Steins;Gate time travel done right", shouldBlock: false },
    { text: "Code Geass ending is perfect", shouldBlock: false },
    { text: "Death Note first half is perfect", shouldBlock: false },
    { text: "Monster is a masterclass in thriller", shouldBlock: false },
    { text: "Berserk manga is brutal perfection", shouldBlock: false },
    { text: "Vagabond art is gorgeous", shouldBlock: false },
    { text: "Oyasumi Punpun is depressing", shouldBlock: false },
    { text: "Chainsaw Man manga is unhinged", shouldBlock: false },
    { text: "Dandadan is wildly entertaining", shouldBlock: false },
    { text: "Blue Lock is hype", shouldBlock: false },
    { text: "Haikyu!! is motivational", shouldBlock: false },
    { text: "Your Name made me cry", shouldBlock: false },
    { text: "A Silent Voice is emotional", shouldBlock: false },
    { text: "Violet Evergarden is beautiful", shouldBlock: false },
    { text: "Made in Abyss is deceptively dark", shouldBlock: false },
    { text: "Promised Neverland season 1 is tense", shouldBlock: false },
    { text: "Tokyo Ghoul manga is better", shouldBlock: false },
    { text: "Parasyte is underrated", shouldBlock: false },
    { text: "Erased is a thriller done right", shouldBlock: false },
    { text: "Re:Zero suffering is real", shouldBlock: false },
    { text: "Konosuba is hilarious", shouldBlock: false },
    { text: "Kaguya-sama is rom-com perfection", shouldBlock: false },
    { text: "Bocchi the Rock is relatable", shouldBlock: false },
    { text: "K-On is wholesome", shouldBlock: false },
    { text: "Lucky Star is nostalgic", shouldBlock: false },
    { text: "Nichijou comedy is absurd", shouldBlock: false },

    { text: "Succession ending was perfect", shouldBlock: false },
    { text: "Better Call Saul is a masterpiece", shouldBlock: false },
    { text: "The Wire is essential viewing", shouldBlock: false },
    { text: "Sopranos started it all", shouldBlock: false },
    { text: "The Office is comfort TV", shouldBlock: false },
    { text: "Parks and Rec is wholesome", shouldBlock: false },
    { text: "Community meta humor is brilliant", shouldBlock: false },
    { text: "30 Rock is underrated", shouldBlock: false },
    { text: "Arrested Development layered comedy", shouldBlock: false },
    { text: "It's Always Sunny is consistent", shouldBlock: false },
    { text: "Curb Your Enthusiasm is cringe comedy", shouldBlock: false },
    { text: "Seinfeld holds up", shouldBlock: false },
    { text: "Friends is dated but nostalgic", shouldBlock: false },
    { text: "How I Met Your Mother ending though", shouldBlock: false },
    { text: "The Bear is stressful excellence", shouldBlock: false },
    { text: "Severance is mind-bending", shouldBlock: false },
    { text: "Andor is Star Wars at its best", shouldBlock: false },
    { text: "House of the Dragon is solid", shouldBlock: false },
    { text: "Rings of Power is divisive", shouldBlock: false },
    { text: "Wheel of Time adaptation is rough", shouldBlock: false },
    { text: "The Witcher casting is good", shouldBlock: false },
    { text: "Shadow and Bone is YA done well", shouldBlock: false },
    { text: "Sandman adaptation is faithful", shouldBlock: false },
    { text: "Good Omens is delightful", shouldBlock: false },
    { text: "Wednesday is surprisingly good", shouldBlock: false },
    { text: "Squid Game phenomenon was wild", shouldBlock: false },
    { text: "Alice in Borderland is intense", shouldBlock: false },
    { text: "Dark is confusing but good", shouldBlock: false },
    { text: "1899 got cancelled rip", shouldBlock: false },
    { text: "Money Heist was overrated", shouldBlock: false },

    { text: "let's fucking go", shouldBlock: false },
    { text: "hell yeah we did it", shouldBlock: false },
    { text: "that's what I'm talking about", shouldBlock: false },
    { text: "gg ez no re", shouldBlock: false },
    { text: "wp team", shouldBlock: false },
    { text: "nice shot", shouldBlock: false },
    { text: "clean play", shouldBlock: false },
    { text: "insane reaction time", shouldBlock: false },
    { text: "cracked aim", shouldBlock: false },
    { text: "this player is nuts", shouldBlock: false },
    { text: "pro gamer move", shouldBlock: false },
    { text: "200 IQ play", shouldBlock: false },
    { text: "galaxy brain moment", shouldBlock: false },
    { text: "big brain energy", shouldBlock: false },
    { text: "smooth brain no thoughts", shouldBlock: false },
    { text: "one braincell bouncing", shouldBlock: false },
    { text: "no thoughts head empty", shouldBlock: false },
    { text: "vibing and thriving", shouldBlock: false },
    { text: "living my best life", shouldBlock: false },
    { text: "main character moment", shouldBlock: false },
    { text: "plot armor activated", shouldBlock: false },
    { text: "built different", shouldBlock: false },
    { text: "simply better", shouldBlock: false },
    { text: "skill issue for them", shouldBlock: false },
    { text: "outplayed outskilled", shouldBlock: false },
    { text: "owned and pwned", shouldBlock: false },
    { text: "rekt", shouldBlock: false },
    { text: "360 no-scope", shouldBlock: false },
    { text: "mlg pro", shouldBlock: false },
    { text: "mountain dew and doritos", shouldBlock: false },
    { text: "mom get the camera", shouldBlock: false },
    { text: "oh baby a triple", shouldBlock: false },
    { text: "wombo combo", shouldBlock: false },
    { text: "that ain't falco", shouldBlock: false },
    { text: "happy feet", shouldBlock: false },
    { text: "where you at", shouldBlock: false },
    { text: "destruction", shouldBlock: false },
    { text: "brutal savage rekt", shouldBlock: false },
    { text: "calculated", shouldBlock: false },
    { text: "what a save", shouldBlock: false },
    { text: "nice one", shouldBlock: false },
    { text: "no problem", shouldBlock: false },
    { text: "close one", shouldBlock: false },
    { text: "whoops", shouldBlock: false },
    { text: "oops", shouldBlock: false },
    { text: "my bad", shouldBlock: false },
    { text: "sorry", shouldBlock: false },
    { text: "no worries", shouldBlock: false },
    { text: "all good", shouldBlock: false },

    { text: "get good scrub (joking)", shouldBlock: false },
    { text: "skill issue lol", shouldBlock: false },
    { text: "cope and seethe /s", shouldBlock: false },
    { text: "mad cuz bad", shouldBlock: false },
    { text: "stay mad", shouldBlock: false },
    { text: "salt shaker", shouldBlock: false },
    { text: "salty much", shouldBlock: false },
    { text: "tilted off the planet", shouldBlock: false },
    { text: "mald harder", shouldBlock: false },
    { text: "touch grass reminder", shouldBlock: false },
    { text: "go outside bestie", shouldBlock: false },
    { text: "shower check", shouldBlock: false },
    { text: "hydration check", shouldBlock: false },
    { text: "posture check", shouldBlock: false },
    { text: "blink reminder", shouldBlock: false },
    { text: "you dropped this king 👑", shouldBlock: false },
    { text: "based", shouldBlock: false },
    { text: "cringe", shouldBlock: false },
    { text: "ratio", shouldBlock: false },
    { text: "L take", shouldBlock: false },
    { text: "W", shouldBlock: false },
    { text: "massive L", shouldBlock: false },
    { text: "huge W", shouldBlock: false },
    { text: "common W", shouldBlock: false },
    { text: "rare L", shouldBlock: false },

    { text: "I'm getting farmed", shouldBlock: false },
    { text: "spawn camped again", shouldBlock: false },
    { text: "sweaty lobby", shouldBlock: false },
    { text: "try-hards everywhere", shouldBlock: false },
    { text: "smurf account detected", shouldBlock: false },
    { text: "ranked anxiety", shouldBlock: false },
    { text: "RNG blessed me", shouldBlock: false },
    { text: "RNG screwed me", shouldBlock: false },
    { text: "loot luck is trash", shouldBlock: false },
    { text: "drop rates are awful", shouldBlock: false },
    { text: "pity system when", shouldBlock: false },
    { text: "gacha salt is real", shouldBlock: false },
    { text: "whaled for this character", shouldBlock: false },
    { text: "F2P btw", shouldBlock: false },
    { text: "pay to win mechanics", shouldBlock: false },
    { text: "microtransactions ruined it", shouldBlock: false },
    { text: "cosmetics only is fine", shouldBlock: false },
    { text: "battle pass worth it", shouldBlock: false },
    { text: "season rewards are mid", shouldBlock: false },
    { text: "nerf incoming", shouldBlock: false },
    { text: "buff this please", shouldBlock: false },
    { text: "meta is stale", shouldBlock: false },
    { text: "patch notes dropped", shouldBlock: false },
    { text: "hotfix needed", shouldBlock: false },
    { text: "servers are down", shouldBlock: false },
    { text: "maintenance extended", shouldBlock: false },
    { text: "compensation when", shouldBlock: false },
    { text: "rollback happening", shouldBlock: false },
    { text: "save file corrupted", shouldBlock: false },
    { text: "progress lost rip", shouldBlock: false },

    { text: "death metal is intense", shouldBlock: false },
    { text: "black metal atmosphere", shouldBlock: false },
    { text: "doom metal is heavy", shouldBlock: false },
    { text: "thrash metal riffs", shouldBlock: false },
    { text: "power metal is epic", shouldBlock: false },
    { text: "nu metal nostalgia", shouldBlock: false },
    { text: "metalcore breakdowns", shouldBlock: false },
    { text: "deathcore is brutal", shouldBlock: false },
    { text: "grindcore is chaos", shouldBlock: false },
    { text: "post-hardcore emotion", shouldBlock: false },
    { text: "screamo vocals are tough", shouldBlock: false },
    { text: "emo phase never ended", shouldBlock: false },
    { text: "pop punk is fun", shouldBlock: false },
    { text: "punk rock energy", shouldBlock: false },
    { text: "hardcore punk aggression", shouldBlock: false },
    { text: "ska is underrated", shouldBlock: false },
    { text: "reggae vibes", shouldBlock: false },
    { text: "indie rock aesthetic", shouldBlock: false },
    { text: "alternative rock variety", shouldBlock: false },
    { text: "grunge era was peak", shouldBlock: false },
    { text: "shoegaze is atmospheric", shouldBlock: false },
    { text: "post-rock builds", shouldBlock: false },
    { text: "math rock time signatures", shouldBlock: false },
    { text: "prog rock is complex", shouldBlock: false },
    { text: "classic rock never dies", shouldBlock: false },
    { text: "psychedelic rock trips", shouldBlock: false },
    { text: "blues rock soul", shouldBlock: false },
    { text: "jazz fusion is wild", shouldBlock: false },
    { text: "smooth jazz relaxing", shouldBlock: false },
    { text: "bebop is technical", shouldBlock: false },
    { text: "hip hop lyricism", shouldBlock: false },
    { text: "trap beats bang", shouldBlock: false },
    { text: "drill is dark", shouldBlock: false },
    { text: "boom bap classic", shouldBlock: false },
    { text: "lo-fi chill vibes", shouldBlock: false },
    { text: "vaporwave aesthetic", shouldBlock: false },
    { text: "synthwave nostalgia", shouldBlock: false },
    { text: "outrun vibes", shouldBlock: false },
    { text: "darkwave atmosphere", shouldBlock: false },
    { text: "industrial harsh", shouldBlock: false },
    { text: "EBM is danceable", shouldBlock: false },
    { text: "techno minimalism", shouldBlock: false },
    { text: "house music grooves", shouldBlock: false },
    { text: "trance euphoria", shouldBlock: false },
    { text: "drum and bass tempo", shouldBlock: false },
    { text: "dubstep wubs", shouldBlock: false },
    { text: "riddim is heavy", shouldBlock: false },
    { text: "future bass colorful", shouldBlock: false },
    { text: "chillstep relaxing", shouldBlock: false },
    { text: "ambient soundscapes", shouldBlock: false },
    { text: "drone music meditative", shouldBlock: false },

    { text: "PC master race but consoles are fine", shouldBlock: false },
    { text: "PlayStation exclusives are great", shouldBlock: false },
    { text: "Xbox Game Pass is value", shouldBlock: false },
    { text: "Nintendo games are timeless", shouldBlock: false },
    { text: "Steam sales are dangerous", shouldBlock: false },
    { text: "Epic Games free games", shouldBlock: false },
    { text: "GOG DRM-free is nice", shouldBlock: false },
    { text: "Itch.io indie gems", shouldBlock: false },
    { text: "controller vs keyboard", shouldBlock: false },
    { text: "ultrawide monitor advantage", shouldBlock: false },
    { text: "high refresh rate gaming", shouldBlock: false },
    { text: "RTX graphics are pretty", shouldBlock: false },
    { text: "AMD vs NVIDIA debate", shouldBlock: false },
    { text: "Intel vs AMD CPUs", shouldBlock: false },
    { text: "RGB makes it faster", shouldBlock: false },
    { text: "water cooling looks cool", shouldBlock: false },
    { text: "air cooling is reliable", shouldBlock: false },
    { text: "SSD load times", shouldBlock: false },
    { text: "NVMe speeds are wild", shouldBlock: false },
    { text: "DDR5 RAM benefits", shouldBlock: false },

    { text: "this community is so supportive", shouldBlock: false },
    { text: "everyone here is friendly", shouldBlock: false },
    { text: "wholesome interactions", shouldBlock: false },
    { text: "helpful community members", shouldBlock: false },
    { text: "thanks for the advice", shouldBlock: false },
    { text: "appreciate the help", shouldBlock: false },
    { text: "learned something new", shouldBlock: false },
    { text: "great explanation", shouldBlock: false },
    { text: "makes sense now", shouldBlock: false },
    { text: "never thought of it that way", shouldBlock: false },
    { text: "interesting perspective", shouldBlock: false },
    { text: "valid point", shouldBlock: false },
    { text: "I see what you mean", shouldBlock: false },
    { text: "that's fair", shouldBlock: false },
    { text: "can't argue with that", shouldBlock: false },
    { text: "you're right", shouldBlock: false },
    { text: "good catch", shouldBlock: false },
    { text: "didn't notice that", shouldBlock: false },
    { text: "sharp eye", shouldBlock: false },
    { text: "attention to detail", shouldBlock: false },
    { text: "well researched", shouldBlock: false },
    { text: "quality content", shouldBlock: false },
    { text: "effort post appreciated", shouldBlock: false },
    { text: "saved for later", shouldBlock: false },
    { text: "bookmarked", shouldBlock: false },
    { text: "sharing with friends", shouldBlock: false },
    { text: "deserves more upvotes", shouldBlock: false },
    { text: "underrated comment", shouldBlock: false },
    { text: "this should be top", shouldBlock: false },
    { text: "best response here", shouldBlock: false },

    { text: "you're so fucking useless", shouldBlock: true },
    { text: "complete waste of time talking to you", shouldBlock: true },
    { text: "brain damaged or just stupid", shouldBlock: true },
    { text: "how do you function", shouldBlock: true },
    { text: "genuinely impressed by your incompetence", shouldBlock: true },
    { text: "you're beyond help", shouldBlock: true },
    { text: "hopeless case", shouldBlock: true },
    { text: "you're a lost cause", shouldBlock: true },
    { text: "giving up on you", shouldBlock: true },
    { text: "you're impossible", shouldBlock: true },
    { text: "waste of my time", shouldBlock: true },
    { text: "why do you even exist", shouldBlock: true },
    { text: "what's wrong with you", shouldBlock: true },
    { text: "something is seriously wrong with you", shouldBlock: true },
    { text: "you need professional help", shouldBlock: true },
    { text: "seek therapy immediately", shouldBlock: true },
    { text: "you're mentally ill", shouldBlock: true },
    { text: "you're psychotic", shouldBlock: true },
    { text: "you're delusional", shouldBlock: true },
    { text: "living in fantasy land", shouldBlock: true },
    { text: "detached from reality", shouldBlock: true },
    { text: "out of touch with the world", shouldBlock: true },
    { text: "your opinion is worthless", shouldBlock: true },
    { text: "nobody asked for your input", shouldBlock: true },
    { text: "keep your mouth shut", shouldBlock: true },
    { text: "shut the fuck up", shouldBlock: true },
    { text: "nobody cares what you think", shouldBlock: true },
    { text: "your thoughts mean nothing", shouldBlock: true },
    { text: "irrelevant and ignored", shouldBlock: true },
    { text: "you don't matter", shouldBlock: true },

    { text: "that game mechanic kills you instantly", shouldBlock: false },
    { text: "this bug is killing the experience", shouldBlock: false },
    { text: "server lag killed my run", shouldBlock: false },
    { text: "that plot twist murdered me emotionally", shouldBlock: false },
    { text: "the finale destroyed me in the best way", shouldBlock: false },
    { text: "character death hit different", shouldBlock: false },
    { text: "spoilers killed the surprise", shouldBlock: false },
    { text: "that jumpscare got me", shouldBlock: false },
    { text: "horror game scared the shit out of me", shouldBlock: false },
    { text: "nightmare fuel content", shouldBlock: false },

    { text: "Zelda Tears of the Kingdom physics", shouldBlock: false },
    { text: "Resident Evil 4 Remake is perfect", shouldBlock: false },
    { text: "Street Fighter 6 rollback netcode", shouldBlock: false },
    { text: "Tekken 8 graphics are insane", shouldBlock: false },
    { text: "Mortal Kombat fatalities are brutal", shouldBlock: false },
    { text: "Guilty Gear Strive is gorgeous", shouldBlock: false },
    { text: "Dragon Ball FighterZ is hype", shouldBlock: false },
    { text: "Super Smash Bros Ultimate roster", shouldBlock: false },
    { text: "Splatoon 3 is colorful chaos", shouldBlock: false },
    { text: "Mario Kart 8 tracks are well designed", shouldBlock: false },
    { text: "Pokemon Legends Arceus was refreshing", shouldBlock: false },
    { text: "Fire Emblem Engage is tactical", shouldBlock: false },
    { text: "Xenoblade Chronicles is ambitious", shouldBlock: false },
    { text: "Monster Hunter Rise is accessible", shouldBlock: false },
    { text: "Diablo 4 endgame needs work", shouldBlock: false },
    { text: "Path of Exile complexity is deep", shouldBlock: false },
    { text: "Grim Dawn build variety", shouldBlock: false },
    { text: "Last Epoch crafting system", shouldBlock: false },
    { text: "Warframe grind is eternal", shouldBlock: false },
    { text: "Destiny 2 raiding is fun", shouldBlock: false },
];

async function runTests() {
    console.log(`Running ${testCases.length} tests...\n`);
    console.log('='.repeat(100));
    
    let passed = 0;
    let failed = 0;
    let falsePositives = 0;
    let falseNegatives = 0;
    
    const failures = [];
    
    for (let i = 0; i < testCases.length; i++) {
        const testCase = testCases[i];
        const result = await AI.checkToxicity(testCase.text);
        const actuallyBlocked = result.isToxic;
        const correct = actuallyBlocked === testCase.shouldBlock;
        
        if (correct) {
            passed++;
        } else {
            failed++;
            if (actuallyBlocked && !testCase.shouldBlock) {
                falsePositives++;
            } else {
                falseNegatives++;
            }
            failures.push({
                text: testCase.text,
                expected: testCase.shouldBlock ? 'BLOCK' : 'ALLOW',
                actual: actuallyBlocked ? 'BLOCKED' : 'ALLOWED',
                score: result.score,
                reason: result.reason
            });
        }

        if ((i + 1) % 100 === 0) {
            console.log(`Progress: ${i + 1}/${testCases.length} tests completed...`);
        }
    }
    
    console.log('='.repeat(100));
    console.log(`\nRESULTS:`);
    console.log(`Total Tests: ${testCases.length}`);
    console.log(`Passed: ${passed} (${((passed / testCases.length) * 100).toFixed(1)}%)`);
    console.log(`Failed: ${failed} (${((failed / testCases.length) * 100).toFixed(1)}%)`);
    console.log(`   - False Positives (blocked good): ${falsePositives}`);
    console.log(`   - False Negatives (allowed bad): ${falseNegatives}`);
    
    if (failures.length > 0) {
        console.log(`\nFAILURES (showing first 20):\n`);
        failures.slice(0, 20).forEach((failure, idx) => {
            console.log(`${idx + 1}. Expected: ${failure.expected} | Got: ${failure.actual}`);
            console.log(`   Text: "${failure.text}"`);
            console.log(`   Score: ${failure.score.toFixed(3)} | Reason: ${failure.reason}\n`);
        });
        
        if (failures.length > 20) {
            console.log(`... and ${failures.length - 20} more failures`);
        }
    }
    
    console.log('\n' + '='.repeat(100));
}

runTests().catch(console.error);